# Configuration file

# stake_amount = amount of stake the bot will use for each trade
# if stake_amount = "unlimited", this configuration will allow increasing/decreasing stakes depending on the performance
# of the bot (lower stake if the bot is losing, higher stakes if the bot has a winning record since higher balances are available), 
# and will result in profit compounding.
# or if a static number is defined, that is the amount per trade
# stake_amount_type = 500
stake_amount_type: "unlimited"

# max number of open positions
# if tradable balance = 1000 and max_number_of_open_positions = 10, the stake_amount = 1000/10 = 100 
max_number_of_open_positions: 10

# tradable percentage of the balance
# for example: if you want to run 3 bot instances (1h, 4h and 1D), you can set the percentage of the total balance to be allocated to all the bots.
tradable_balance_ratio: 1

# minimum position size
# if trade_against = BUSD or USDT => min_position_size: 20
# if trade_against = BTC => min_position_size: 0.001
min_position_size: 0.001

# trade top X performance coins
trade_top_performance: 30

# trade against BUSD, USDT or BTC
trade_against: "BTC"

# Risk Management 
# Set stop loss to automatically sell if its price falls below a certain percentage.
# If no stop loss
# examples:
# stop_loss = 0 => will not use stop loss. The stop loss used will be triggered when slow_ema > fast_ema
# stop_loss = 10 => 10%   
stop_loss: 0
